theme: jekyll-theme-cayman
title: Simon Dold
description: >
  I am a PhD student in the Artificial Intelligence group at the University of Basel, where I have been working since 2022 under the supervision of Prof. Dr. Malte Helmert.
  I completed my Master's in Computer Science here in 2021.
  My research interests center on potential heuristics and proof logging in automated planning.
